location                  = "northeurope"
resource_group_name       = "sangammlops18"
storage_account_name      = "sangammlopstsa18"
application_insights_name = "sangammlopsappinsights18"
key_vault_name            = "sangammlopskeyvault18"
ml_workspace_name         = "sangammlopsworkspace18"
