name: Deploy Model Training Pipeline

on:
  workflow_dispatch: # Enable manual triggering

jobs:
  deploy-model-training:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Login to Azure using Service Principal Secret
    - name: Login to Azure
      uses: azure/login@v2
      with:
        auth-type: secret
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        client-secret: ${{ secrets.ARM_CLIENT_SECRET }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    # Step 3: Register Environment
    - name: Register Azure ML Environment
      run: |
        az ml environment create --file mlops/azureml/train/train-env.yml \
          --resource-group ${{ secrets.AML_RESOURCE_GROUP }} \
          --workspace-name ${{ secrets.AML_WORKSPACE_NAME }}

    # Step 4: Register Dataset
    - name: Register Azure ML Dataset
      run: |
        az ml data create --file mlops/azureml/train/data.yml \
          --resource-group ${{ secrets.AML_RESOURCE_GROUP }} \
          --workspace-name ${{ secrets.AML_WORKSPACE_NAME }}

    # Step 5: Create Compute Cluster
    - name: Create Compute Cluster
      run: |
        az ml compute create --name cpu-cluster \
          --type AmlCompute \
          --min-instances 0 --max-instances 4 \
          --size Standard_DS3_v2 \
          --resource-group ${{ secrets.AML_RESOURCE_GROUP }} \
          --workspace-name ${{ secrets.AML_WORKSPACE_NAME }}

    # Step 6: Run Model Training Pipeline
    - name: Run Model Training Pipeline
      run: |
        az ml job create --file mlops/azureml/train/pipeline.yml \
          --resource-group ${{ secrets.AML_RESOURCE_GROUP }} \
          --workspace-name ${{ secrets.AML_WORKSPACE_NAME }} \
          --name train-pipeline-job
