name: Deploy and Test Online Endpoint and Deployment

on:
  workflow_dispatch:  # Enables manual triggering of the workflow 
 
jobs:
  deploy-online-endpoint:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Login to Azure using Service Principal Secret
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Install Azure ML CLI Extension
    - name: Install Azure ML CLI Extension
      run: |
        az extension add --name ml -y || az extension update --name ml

    # Step 5: Create or Update Online Endpoint
    - name: Create or Update Online Endpoint
      run: |
        az ml online-endpoint create --file mlops/azureml/deploy/online-endpoint.yml \
          --resource-group ${{ secrets.AML_RESOURCE_GROUP }} \
          --workspace-name ${{ secrets.AML_WORKSPACE_NAME }}

    # Step 6: Create or Update Online Deployment
    - name: Create or Update Online Deployment
      run: |
        az ml online-deployment create --file mlops/azureml/deploy/online-deployment.yml \
          --resource-group ${{ secrets.AML_RESOURCE_GROUP }} \
          --workspace-name ${{ secrets.AML_WORKSPACE_NAME }} \
          --all-traffic


#    # Optional Step 8: Validate the Response (e.g., Check Status or Output)
#    - name: Validate Model Response
#      run: |
#        # Step 1: Get an Authorization Token using Azure CLI
#        token=$(az account get-access-token --resource https://ml.azure.com --query accessToken -o tsv)
#
#        # Step 2: Make the API Request to the Endpoint
#        response=$(curl -s -X POST \
#          -H "Content-Type: application/json" \
#          -H "Authorization: Bearer $token" \
#          -d @mlops/data/taxi-request.json \
#          https://$taxi-fare-online.${{ secrets.AML_WORKSPACE_NAME }}.azurewebsites.net/score)
#
#        # Step 3: Print the Response
#        echo "Model response: $response"