name: Deploy and Test Online Endpoint and Deployment

on:
  workflow_dispatch:  # Enables manual triggering of the workflow 
 
jobs:
  deploy-online-endpoint:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Login to Azure using Service Principal Secret
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Install Azure ML CLI Extension
    - name: Install Azure ML CLI Extension
      run: |
        az extension add --name ml -y || az extension update --name ml

    # Step 5: Create or Update Online Endpoint
    - name: Create or Update Online Endpoint
      run: |
        az ml online-endpoint create --file mlops/azureml/deploy/online-endpoint.yml \
          --resource-group ${{ secrets.AML_RESOURCE_GROUP }} \
          --workspace-name ${{ secrets.AML_WORKSPACE_NAME }}

    # Step 6: Create or Update Online Deployment
    - name: Create or Update Online Deployment
      run: |
        az ml online-deployment create --file mlops/azureml/deploy/online-deployment.yml \
          --resource-group ${{ secrets.AML_RESOURCE_GROUP }} \
          --workspace-name ${{ secrets.AML_WORKSPACE_NAME }} \
          --all-traffic

    # Step 7: Test the Deployed Model using taxi-request.json
    - name: Test Online Endpoint
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.AML_API_KEY }}" \
          -d @mlops/azureml/deploy/taxi-request.json \
          https://$taxi-fare-online.${{ secrets.AML_WORKSPACE_NAME }}.azurewebsites.net/score

    # Optional Step 8: Validate the Response (e.g., Check Status or Output)
    - name: Validate Model Response
      run: |
        response=$(curl -s -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.AML_API_KEY }}" \
          -d @mlops/azureml/deploy/taxi-request.json \
          https://$taxi-fare-online.${{ secrets.AML_WORKSPACE_NAME }}.azurewebsites.net/score)
        
        echo "Model response: $response"
        # Optionally, add logic to check if the response is valid (e.g., status code, expected output)
        if [[ $response == *"error"* ]]; then
          echo "Test failed!"
          exit 1  
        else  
          echo "Test passed!"  
        fi 
