name: Deploy Model to Online Endpoint

on:
  workflow_dispatch: # Enable manual triggering of this pipeline

jobs:
  deploy-online-endpoint:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Login to Azure using Service Principal Secret
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 2.1: Install Azure ML CLI Extension
    - name: Install Azure ML CLI Extension
      run: |
        az extension add --name ml -y || az extension update --name ml

    # Step 3: Create or Update Online Endpoint
    - name: Create or Update Online Endpoint
      run: |
        az ml online-endpoint create --name my-online-endpoint \
          --file mlops/azureml/deploy/endpoint.yml \
          --resource-group ${{ secrets.AML_RESOURCE_GROUP }} \
          --workspace-name ${{ secrets.AML_WORKSPACE_NAME }}

    # Step 4: Deploy Model to Endpoint
    - name: Deploy Model to Endpoint
      run: |
        az ml online-deployment create --name blue-deployment \
          --endpoint-name my-online-endpoint \
          --file mlops/azureml/deploy/deployment.yml \
          --resource-group ${{ secrets.AML_RESOURCE_GROUP }} \
          --workspace-name ${{ secrets.AML_WORKSPACE_NAME }}

    # Step 5: Test the Endpoint with Test Data
    - name: Test Endpoint
      run: |
        # Locate the test data file (assumes it's under the same directory as training data)
        TEST_DATA_PATH="mlops/azureml/train/test_data.json"

        # Extract the endpoint URL dynamically
        ENDPOINT_URL=$(az ml online-endpoint show --name my-online-endpoint \
          --resource-group ${{ secrets.AML_RESOURCE_GROUP }} \
          --workspace-name ${{ secrets.AML_WORKSPACE_NAME }} \
          --query scoring_uri -o tsv)

        # Send the test data to the endpoint using curl
        RESPONSE=$(curl -X POST -H "Content-Type: application/json" \
          -d @$TEST_DATA_PATH $ENDPOINT_URL)
        
        echo "Test Endpoint Response: $RESPONSE"
