name: Deploy Model Training Pipeline

on:
  workflow_dispatch:  # Enables manual trigger of the workflow


jobs:
  register-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          client-secret: ${{ secrets.ARM_CLIENT_SECRET }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Register Environment
        run: |
          az ml environment create \
            --file mlops/azureml/train/train-env.yml \
            --conda-file data-science/environment/train-conda.yml \
            --name training-environment \
            --workspace-name ${{ secrets.AML_WORKSPACE_NAME }} \
            --resource-group ${{ secrets.AML_RESOURCE_GROUP }}

  register-dataset:
    runs-on: ubuntu-latest
    needs: register-environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          client-secret: ${{ secrets.ARM_CLIENT_SECRET }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Register Dataset
        run: |
          az ml data create \
            --name taxi-data \
            --path mlops/azureml/train/data.yml \
            --workspace-name ${{ secrets.AML_WORKSPACE_NAME }} \
            --resource-group ${{ secrets.AML_RESOURCE_GROUP }}

  create-compute:
    runs-on: ubuntu-latest
    needs: register-dataset
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          client-secret: ${{ secrets.ARM_CLIENT_SECRET }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Create Compute
        run: |
          az ml compute create \
            --name cpu-cluster \
            --type AmlCompute \
            --size Standard_DS3_v2 \
            --min-instances 0 \
            --max-instances 1 \
            --workspace-name ${{ secrets.AML_WORKSPACE_NAME }} \
            --resource-group ${{ secrets.AML_RESOURCE_GROUP }}

  run-model-training-pipeline:
    runs-on: ubuntu-latest
    needs: create-compute
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          client-secret: ${{ secrets.ARM_CLIENT_SECRET }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Run Model Training Pipeline
        run: |
          az ml job create \
            --file mlops/azureml/train/pipeline.yml \
            --workspace-name ${{ secrets.AML_WORKSPACE_NAME }} \
            --resource-group ${{ secrets.AML_RESOURCE_GROUP }}
