name: Deploy Azure Resources

on:
  workflow_dispatch:  # Enables manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_resource_group_name: ${{ secrets.TF_VAR_resource_group_name }}
      TF_VAR_location: ${{ secrets.TF_VAR_location }}
      TF_VAR_storage_account_name: ${{ secrets.TF_VAR_storage_account_name }}
      TF_VAR_account_tier: ${{ secrets.TF_VAR_account_tier }}
      TF_VAR_account_replication_type: ${{ secrets.TF_VAR_account_replication_type }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.7  # Change to your preferred version

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply tfplan
